# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/web-app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/web-app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/web-app/CMakeFiles /home/ubuntu/web-app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/web-app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named web_app

# Build rule for target.
web_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 web_app
.PHONY : web_app

# fast build rule for target.
web_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/build
.PHONY : web_app/fast

#=============================================================================
# Target rules for targets named static-analysis

# Build rule for target.
static-analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 static-analysis
.PHONY : static-analysis

# fast build rule for target.
static-analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static-analysis.dir/build.make CMakeFiles/static-analysis.dir/build
.PHONY : static-analysis/fast

#=============================================================================
# Target rules for targets named memory-profiling

# Build rule for target.
memory-profiling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory-profiling
.PHONY : memory-profiling

# fast build rule for target.
memory-profiling/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory-profiling.dir/build.make CMakeFiles/memory-profiling.dir/build
.PHONY : memory-profiling/fast

#=============================================================================
# Target rules for targets named doc_doxygen

# Build rule for target.
doc_doxygen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc_doxygen
.PHONY : doc_doxygen

# fast build rule for target.
doc_doxygen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc_doxygen.dir/build.make CMakeFiles/doc_doxygen.dir/build
.PHONY : doc_doxygen/fast

#=============================================================================
# Target rules for targets named package

# Build rule for target.
package: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 package
.PHONY : package

# fast build rule for target.
package/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/package.dir/build.make CMakeFiles/package.dir/build
.PHONY : package/fast

#=============================================================================
# Target rules for targets named all-tools

# Build rule for target.
all-tools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all-tools
.PHONY : all-tools

# fast build rule for target.
all-tools/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all-tools.dir/build.make CMakeFiles/all-tools.dir/build
.PHONY : all-tools/fast

#=============================================================================
# Target rules for targets named bear

# Build rule for target.
bear: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bear
.PHONY : bear

# fast build rule for target.
bear/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bear.dir/build.make CMakeFiles/bear.dir/build
.PHONY : bear/fast

src/config_loader.o: src/config_loader.c.o
.PHONY : src/config_loader.o

# target to build an object file
src/config_loader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/config_loader.c.o
.PHONY : src/config_loader.c.o

src/config_loader.i: src/config_loader.c.i
.PHONY : src/config_loader.i

# target to preprocess a source file
src/config_loader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/config_loader.c.i
.PHONY : src/config_loader.c.i

src/config_loader.s: src/config_loader.c.s
.PHONY : src/config_loader.s

# target to generate assembly for a file
src/config_loader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/config_loader.c.s
.PHONY : src/config_loader.c.s

src/constants.o: src/constants.c.o
.PHONY : src/constants.o

# target to build an object file
src/constants.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/constants.c.o
.PHONY : src/constants.c.o

src/constants.i: src/constants.c.i
.PHONY : src/constants.i

# target to preprocess a source file
src/constants.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/constants.c.i
.PHONY : src/constants.c.i

src/constants.s: src/constants.c.s
.PHONY : src/constants.s

# target to generate assembly for a file
src/constants.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/constants.c.s
.PHONY : src/constants.c.s

src/env_loader.o: src/env_loader.c.o
.PHONY : src/env_loader.o

# target to build an object file
src/env_loader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/env_loader.c.o
.PHONY : src/env_loader.c.o

src/env_loader.i: src/env_loader.c.i
.PHONY : src/env_loader.i

# target to preprocess a source file
src/env_loader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/env_loader.c.i
.PHONY : src/env_loader.c.i

src/env_loader.s: src/env_loader.c.s
.PHONY : src/env_loader.s

# target to generate assembly for a file
src/env_loader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/env_loader.c.s
.PHONY : src/env_loader.c.s

src/error_handler.o: src/error_handler.c.o
.PHONY : src/error_handler.o

# target to build an object file
src/error_handler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/error_handler.c.o
.PHONY : src/error_handler.c.o

src/error_handler.i: src/error_handler.c.i
.PHONY : src/error_handler.i

# target to preprocess a source file
src/error_handler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/error_handler.c.i
.PHONY : src/error_handler.c.i

src/error_handler.s: src/error_handler.c.s
.PHONY : src/error_handler.s

# target to generate assembly for a file
src/error_handler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/error_handler.c.s
.PHONY : src/error_handler.c.s

src/garbage_collector.o: src/garbage_collector.c.o
.PHONY : src/garbage_collector.o

# target to build an object file
src/garbage_collector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/garbage_collector.c.o
.PHONY : src/garbage_collector.c.o

src/garbage_collector.i: src/garbage_collector.c.i
.PHONY : src/garbage_collector.i

# target to preprocess a source file
src/garbage_collector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/garbage_collector.c.i
.PHONY : src/garbage_collector.c.i

src/garbage_collector.s: src/garbage_collector.c.s
.PHONY : src/garbage_collector.s

# target to generate assembly for a file
src/garbage_collector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/garbage_collector.c.s
.PHONY : src/garbage_collector.c.s

src/logger.o: src/logger.c.o
.PHONY : src/logger.o

# target to build an object file
src/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/logger.c.o
.PHONY : src/logger.c.o

src/logger.i: src/logger.c.i
.PHONY : src/logger.i

# target to preprocess a source file
src/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/logger.c.i
.PHONY : src/logger.c.i

src/logger.s: src/logger.c.s
.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/logger.c.s
.PHONY : src/logger.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/main.c.s
.PHONY : src/main.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/utils.c.s
.PHONY : src/utils.c.s

src/validator.o: src/validator.c.o
.PHONY : src/validator.o

# target to build an object file
src/validator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/validator.c.o
.PHONY : src/validator.c.o

src/validator.i: src/validator.c.i
.PHONY : src/validator.i

# target to preprocess a source file
src/validator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/validator.c.i
.PHONY : src/validator.c.i

src/validator.s: src/validator.c.s
.PHONY : src/validator.s

# target to generate assembly for a file
src/validator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_app.dir/build.make CMakeFiles/web_app.dir/src/validator.c.s
.PHONY : src/validator.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... all-tools"
	@echo "... bear"
	@echo "... doc_doxygen"
	@echo "... memory-profiling"
	@echo "... package"
	@echo "... static-analysis"
	@echo "... web_app"
	@echo "... src/config_loader.o"
	@echo "... src/config_loader.i"
	@echo "... src/config_loader.s"
	@echo "... src/constants.o"
	@echo "... src/constants.i"
	@echo "... src/constants.s"
	@echo "... src/env_loader.o"
	@echo "... src/env_loader.i"
	@echo "... src/env_loader.s"
	@echo "... src/error_handler.o"
	@echo "... src/error_handler.i"
	@echo "... src/error_handler.s"
	@echo "... src/garbage_collector.o"
	@echo "... src/garbage_collector.i"
	@echo "... src/garbage_collector.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/validator.o"
	@echo "... src/validator.i"
	@echo "... src/validator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

