# Use the Alpine Linux base image
FROM docker.io/alpine:latest

# Install necessary packages
RUN apk update && apk add --no-cache \
    build-base \
    musl \
        musl-utils \
        musl-obstack-dev \
        musl-libintl \
        musl-nscd-dev \
        musl-fts-dev \
        gdb \
        valgrind \
        musl-legacy-error \
        dropbear \
    dropbear-dbclient \
    dropbear-ssh \
    gpg \
    gpg-agent \
    pinentry \
        tree \
    git \
    ca-certificates \
        musl-locales \
        musl-locales-lang \
        cunit-dev

# Set locale environment variables
ENV LANG=en_AU.UTF-8 \
        LC_ALL=en_AU.UTF-8 \
        LANGUAGE=en_AU.UTF:en

# Add a user for non-root execution
RUN adduser -D appuser -u 1000 -g 1000 appuser
USER appuser

# Expose port 80
EXPOSE 80
