FROM debian:stable-slim

# Install essential packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    clang-format \
    clang-tidy \
    git \
    dropbear \
    gnupg \
    tree \
    ne \
    shellcheck \
    cppcheck \
    clang \
    llvm \
    cmake \
    valgrind \
    splint \
    indent \
    groff \
    binutils \
    wget \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN wget https://musl.libc.org/releases/musl-1.2.5.tar.gz && \
    tar -xzf musl-1.2.5.tar.gz && \
    cd musl-1.2.5 && \
    ./configure --prefix=/usr/local/musl --target=x86_64-linux-gnu && \
    make && \
    make install && \
    cd .. && \
    rm -rf musl-1.2.5 musl-1.2.5.tar.gz

# Set up a user for development
RUN useradd -ms /bin/bash devuser

# Switch to the new user
USER devuser
WORKDIR /home/devuser

# Expose SSH and GPG for use in the container
RUN mkdir -p ~/.ssh && chmod 700 ~/.ssh
RUN mkdir -p ~/.gnupg && chmod 700 ~/.gnupg

# Set the default command to start a shell
CMD ["/bin/sh"]
