.TH APP 1 "November 2024" "Version 1.0" "App Manual"
.SH NAME
app \- a brief description of your program
.SH SYNOPSIS
.B app
.RI [ options ]
.SH DESCRIPTION
A more detailed description of what your program does.
.SH OPTIONS
.TP
.B \-h
Display help information.
.TP
.B \-v
Display version information.
.SH AUTHOR
Written by Your Name.
.SH COPYRIGHT
Copyright 2024 Enveng Group.
Licensed under the AGPL-3.0-or-later.
