.TH MY_PROGRAM 1 "October 2024" "Version 1.0" "My Program Manual"
.SH NAME
my_program \- a brief description of your program
.SH SYNOPSIS
.B my_program
.RI [ options ]
.SH DESCRIPTION
A more detailed description of what your program does.
.SH OPTIONS
.TP
.B \-h
Display help information.
.TP
.B \-v
Display version information.
.SH AUTHOR
Written by Your Name.
.SH COPYRIGHT
Copyright 2024 Enveng Group.
Licensed under the AGPL-3.0-or-later.
